---
title: "University Rankings"
format: 
  html:
    output-file: "index.html"
editor: visual
---

##  Problem 1 
```{r}
df<- read.csv("http://manctsui.github.io/datasets/timesData.csv")
head(df)
nrow(df)
```

## Problem 2
```{r}
##grep("Los Angeles", df$university_name, value = TRUE)
ucla <- df[grep("Los Angeles", df$university_name),c("year","world_rank")]
ucla
```

## Problem 3

```{r}
ucla$world<-as.numeric(ucla$world_rank)
plot(ucla$year,ucla$world_rank,
     main="UCLA World Ranking",
     xlab="Year",
     ylab="World Rank",
     type="l",
     )
```

##Problem 4
```{r}
#| layout-ncol: 2
ucla$world<-as.numeric(ucla$world_rank)
plot(ucla$year,ucla$world_rank,
     main="UCLA World Ranking",
     xlab="Year",
     ylab="World Rank",
     type="l",
     )
Berkeley <- df[grep("Berkeley", df$university_name),c("year","world_rank")]
Berkeley$world_rank<-as.numeric(Berkeley$world_rank)
plot(Berkeley$year,Berkeley$world_rank,
     main="Berkeley World Ranking",
     xlab="Year",
     ylab="World Rank",
     type="l",
     )
```

##Problem 5
```{r}
library(dplyr)
top50<-df|>
  mutate(rank_num=as.numeric(world_rank))|>
  filter( country=="United States of America", rank_num<=50)|>
  group_by(year)|>
  summarise(number_top50=n())
top50
```
